name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: PHP ${{ matrix.php }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        php:
          - "7.3"
          - "7.4"
          - "8.0"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: php-${{ matrix.php}}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php-${{ matrix.php}}-composer-

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      - name: Run tests with codeception
        run: vendor/bin/codecept run
